Fix: Add "rotationMatrix" function type
josdejong/mathjs pull request #2860
Opened 2022-12-08 19:17 UTC by brunoSnoww

Issue: #2803 

Why: The type for the function rotationMatrix was missing in index.d.ts

What: Add such type in index.d.ts and a little test on testTypes.ts

Suggestion: Maybe add a type SquareMatrix that extends from Matrix  and the function "rotationMatrix" would return such type ( since rotation matrices are always square ) ?

2022-12-09 10:13 UTC, josdejong requested changes
Thanks @brunoSnoww! I made two small inline comments. 

I have one more question: can you add a usage example to `/test/typescript-tests/testTypes.ts`, so the types are actually tested and guarded?

> Suggestion: Maybe add a type SquareMatrix that extends from Matrix and the function "rotationMatrix" would return such type ( since rotation matrices are always square ) ?

That is an interesting idea. It would require quite some work though, we somehow have to keep track on whether a matrix is a SquareMatrix during calculations. If you think this is worth thinking through, can you open a [Discussion](https://github.com/josdejong/mathjs/discussions) about it?

2022-12-09 10:13 UTC, josdejong commented on types/index.d.ts
> +    rotationMatrix<T extends Matrix>(
I think `T extends Matrix` should be replaced with `T extends MathCollection`: it can return both a Matrix or an Array

2022-12-09 10:13 UTC, josdejong commented on types/index.d.ts
> +      axis?: MathArray | Matrix,
Can be replaced with:

```js
axis?: T
```
(when `T extends MathCollection`)

2022-12-09 13:42 UTC, brunoSnoww commented
Thanks for the feedback @josdejong ! I'll investigate more about the suggestion I made before open a discussion xD

2022-12-09 15:18 UTC, josdejong approved these changes

2022-12-09 15:33 UTC, josdejong commented
👍 

 thanks again!

2022-12-09 15:33 UTC, merged

2023-01-31 17:01 UTC, josdejong commented
published now in `v11.5.1`, thanks again